kind: ConfigMap
apiVersion: v1
metadata:
  name: app-config-rhdh
  namespace: test-devhub-tutorial
data:
  app-config-rhdh.yaml: |
    app:
      title: Red Hat Developer Hub
      baseUrl: https://redhat-developer-hub-test-devhub-tutorial.apps.k8s.dev.local
    integrations:
      github:
        - host: github.com
          token: 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
    auth:
      allowGuestAccess: true
      environment: development
      providers:
        github:
          development:
            clientId: Iv23li29PAaIyHX9oEk5
            clientSecret: 8419063b592e931ec32b4d056605be9950dd9109
    enabled:
      github: true
    kubernetes:
      customResources:
        - group: 'tekton.dev'
          apiVersion: 'v1beta1'
          plural: 'pipelineruns'
        - group: 'tekton.dev'
          apiVersion: 'v1beta1'
          plural: 'taskruns'  
