apiVersion: v1
kind: ServiceAccount
metadata:
  name: backstage-read-only
  namespace: test-devhub-tutorial 
---
kind: Secret
apiVersion: v1
metadata:
  name: backstage-read-only
  annotations:
    kubernetes.io/service-account.name: backstage-read-only  
type: kubernetes.io/service-account-token
